package britanico.kira.Models;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Date;

@Entity
@Table(name = "PS_CLASS_MTG_PAT")
public class PS_CLASS_MTG_PAT {
    @EmbeddedId
    public PS_CLASS_MTG_PAT_ID psClassMtgPatId;
    public String INSTITUTION;
    public String ACAD_GROUP;
    public String SUBJECT;
    public String CATALOG_NBR;
    public String ACAD_CAREER;
    public String DESCR;
    public int CLASS_NBR;
    public String SSR_COMPONENT;
    public String ENRL_STAT;
    public String CLASS_STAT;
    public String CLASS_TYPE;
    public int ASSOCIATED_CLASS;
    public String WAITLIST_DAEMON;
    public String AUTO_ENRL_WAITLIST;
    public String STDNT_SPEC_PERM;
    public String AUTO_ENROLL_SECT_1;
    public String AUTO_ENROLL_SECT_2;
    public String RESECTION;
    public String SCHEDULE_PRINT;
    public String CONSENT;
    public int ENRL_CAP;
    public int WAIT_CAP;
    public int MIN_ENRL;
    public int ENRL_TOT;
    public int WAIT_TOT;
    public int CRS_TOPIC_ID;
    public String PRINT_TOPIC;
    public String ACAD_ORG;
    public int NEXT_STDNT_POSITIN;
    public String EMPLID;
    public String CAMPUS;
    public String LOCATION;
    public String CAMPUS_EVENT_NBR;
    public String INSTRUCTION_MODE;
    public String EQUIV_CRSE_ID;
    public String OVRD_CRSE_EQUIV_ID;
    public int ROOM_CAP_REQUEST;
    public Date START_DT;
    public Date END_DT;
    public Date CANCEL_DT;
    public String PRIM_INSTR_SECT;
    public String COMBINED_SECTION;
    public String HOLIDAY_SCHEDULE;
    public int EXAM_SEAT_SPACING;
    public String DYN_DT_INCLUDE;
    public String DYN_DT_CALC_REQ;
    public String ATTEND_GENERATE;
    public String ATTEND_SYNC_REQD;
    public String FEES_EXIST;
    public String CNCL_IF_STUD_ENRLD;
    public String RCV_FROM_ITEM_TYPE;
    public String AP_BUS_UNIT;
    public String AP_LEDGER;
    public String AP_ACCOUNT;
    public String AP_DEPTID;
    public String AP_PROJ_ID;
    public String AP_PRODUCT;
    public String AP_FUND_CODE;
    public String AP_PROG_CODE;
    public String AP_CLASS_FLD;
    public String AP_AFFILIATE;
    public String AP_OP_UNIT;
    public String AP_ALTACCT;
    public String AP_BUD_REF;
    public String AP_CF1;
    public String AP_CF2;
    public String AP_CF3;
    public String AP_AFF_INT1;
    public String AP_AFF_INT2;
    public String WRITEOFF_BUS_UNIT;
    public String WRITEOFF_LEDGER;
    public String WRITEOFF_ACCOUNT;
    public String WRITEOFF_DEPTID;
    public String WRITEOFF_PROJ_ID;
    public String WRITEOFF_PRODUCT;
    public String WRITEOFF_FUND_CODE;
    public String WRITEOFF_PROG_CODE;
    public String WRITEOFF_CLASS_FLD;
    public String WRITEOFF_AFFILIATE;
    public String WRITEOFF_OP_UNIT;
    public String WRITEOFF_ALTACCT;
    public String WRITEOFF_BUD_REF;
    public String WRITEOFF_CF1;
    public String WRITEOFF_CF2;
    public String WRITEOFF_CF3;
    public String WRITEOFF_AFF_INT1;
    public String WRITEOFF_AFF_INT2;
    public String EXT_WRITEOFF;
    public String GL_INTERFACE_REQ;
    public String LMS_FILE_TYPE;
    public String LMS_GROUP_ID;
    public String LMS_URL;
    public Date LMS_CLASS_EXT_DTTM;
    public Date LMS_ENRL_EXT_DTTM;
    public String LMS_PROVIDER;
    public String SSR_DROP_CONSENT;
}
